server:
    port: 8080

logging:
    level:
        root: info
    pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level %logger{36} - %msg%n"

spring:
    application:
        name: application-service

eureka:
    client:
        serviceUrl:
            defaultZone: http://eureka-server:8761/eureka/
    instance:
        preferIpAddress: true