server:
    port: 8761

logging:
    level:
        root: info
    pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level %logger{36} - %msg%n"

spring:
    application:
        name : eureka-server

eureka:
    client:
        register-with-eureka: false
        fetch-registry: false
